sections:
- title: Major changes
  labels:
    - "release/super-feature"
- title: Complete changelog
  labels:
    - "bug"
    - "enhancement"
    - "dependencies"
template: |
  Add Adminer helm chart template as dependency to Chart.yaml:
  ```yaml
    dependencies:
      - name: adminer
        alias: app
        version: "{{ .Version }}"
        repository: oci://ghcr.io/onecx/charts
  ```

  {{ range $section := .Sections }}{{ if $section.Items }}### {{ $section.GetTitle }}{{ range $item := $section.Items }}
  * [#{{ $item.GetID }}]({{ $item.GetURL }}) - {{ $item.GetTitle }}{{ end }}{{ end }}
  {{ end }}