name: Build Pull Request
on:
  pull_request:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'

jobs:
  docker:
    uses: onecx/ci-common/.github/workflows/docker-build.yml@v1
    secrets: inherit
    with:
      platform: 'linux/amd64,linux/arm64'
      buildx: true    
      push: false
      artifact: ''
      samoDockerFile: Dockerfile
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    needs: docker    
    with:
      helmDir: 'helm'
      artifact: ''
