name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
      - '[0-9]+.x'

jobs:
  docker:
    uses: onecx/ci-common/.github/workflows/docker-build.yml@v1
    secrets: inherit
    with:
      platform: 'linux/amd64,linux/arm64'
      buildx: true    
      push: true
      tags: '{{ .Version }},{{ .Branch }}'
      artifact: '' 
      samoDockerFile: Dockerfile
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    needs: docker
    with:
      push: true
      artifact: ''
      helmDir: 'helm'
  helm-event:
    uses: onecx/ci-product/.github/workflows/helm-send-event.yml@v1
    needs: helm
    secrets: inherit
    with:
      targetRepository: onecx/onecx-develop